# Generated by Django 3.2.15 on 2022-11-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votinginfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedBack',
            new_name='info',
        ),
    ]
